GET http://localhost:3000/api/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTVkOWRlZmYxZGZlYTEwNzA1Nzg3YTkiLCJpYXQiOjE2MzM1NjMyODJ9.5jiYVk0BjDgaCQf1naHzG3QQSXAB1DKo7XyIKGHB7Lo

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
   "username": "Duy",
   "password":"1234"
}

###
PUT http://localhost:3000/api/posts/615dac22eaba603ce7b11ab8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTVkOWRlZmYxZGZlYTEwNzA1Nzg3YTkiLCJpYXQiOjE2MzM1NjMyODJ9.5jiYVk0BjDgaCQf1naHzG3QQSXAB1DKo7XyIKGHB7Lo

{
    "title" : "new title",
    "description" : "changed ",
    "url" :"testing",
    "status" : "learnt"
}

